### ISSUE TITLE
TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is null

### ISSUE THREAD

**Issue by Hash6232** [violentmonkey/rollup-plugin-userscript#8]
While trying to follow the instruction on the readme, I get this error in output and I am not sure how to address it.

***

- Microsoft Windows 10
- Node: v22.5.1
- NPM: 10.8.2 

package.json
```json
{
  ..
  "devDependencies": {
      "rollup": "^4.20.0",
      "rollup-plugin-userscript": "^0.3.2",
      "typescript": "^5.5.4"
    }
}
```
directory tree
```
./
│   package-lock.json
│   package.json
│   rollup.config.mjs
│   tsconfig.json
│   
├───dist
│       my-script.user.js
│                   
└───src
        main.ts
        meta.js
```
rollup.config.mjs
```js
import userscript from 'rollup-plugin-userscript';

export default {
      input: 'src/main.ts',
      output: {
          file: 'dist/my-script.user.js',
          format: 'iife'
      },
      plugins: [ userscript() ]
};

```
main.ts
```ts
import './meta.js?userscript-metadata';

console.log(true);

```
meta.js
```js
// ==UserScript==
// @name        My Script
// @namespace   my-script
// @description Sample desc.
// @match       http://website.com/*
// @version     0.0.1
// @author      -
// ==/UserScript==

```
terminal output
```
npm run build

> my-script@1.0.0 build
> rollup -c


src/main.ts → dist/my-script.user.js...
[!] (plugin userscript-metadata) TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is null.
    at Object.resolveId (file:///C:/Users/User/Documents/my-script/node_modules/rollup-plugin-userscript/dist/index.js:71:11)       
    at async PluginDriver.hookFirstAndGetPlugin (C:\Users\User\Documents\my-script\node_modules\rollup\dist\shared\rollup.js:896:28)
    at async resolveId (C:\Users\User\Documents\my-script\node_modules\rollup\dist\shared\rollup.js:19783:26)
    at async ModuleLoader.resolveId (C:\Users\User\Documents\my-script\node_modules\rollup\dist\shared\rollup.js:19967:15)
    at async C:\Users\User\Documents\my-script\node_modules\rollup\dist\shared\rollup.js:20271:50
```

**Comment by gera2ld** [comment]
Could you provide a minimal reproduction (i.e. a valid repo or project that reproduces the issue)? Thanks.

**Comment by Hash6232** [comment]
Here's a sample project: [test.zip](https://github.com/user-attachments/files/16580483/test.zip)

**Comment by gera2ld** [comment]
Could you try `0.3.3`? Thanks.

**Comment by srdr0p** [comment]
> Could you try `0.3.3`? Thanks.

I have the same problem, after upgrade to 0.3.3, the problem is resolved
